[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = [
  'python manage.py showmigrations',
  'python manage.py migrate --verbosity=3 --run-syncdb',
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python3 run_migrations_now.py && gunicorn worknest.wsgi --log-file -'